name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt-openjdk'

      - name: Set up Android SDK
        uses: reactivecircus/android-emulator-runner@v3
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: |
            ./gradlew assembleDebug
            ./gradlew testDebug

      - name: Build Release
        run: ./gradlew assembleRelease

      - name: Run Tests
        run: ./gradlew test
